language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - '14'
  - node
script:
  - npm run browserslist
  - npm run check:src
  - npm run build
branches:
  except:
    - experimental
cache:
  directories:
    - $HOME/.npm
